//
// Created by xim on 5/11/21.
//

#include "preprocess.h"
#include <stdio.h>
#include <malloc.h>
#include "common.h"

/*
 * In this preprocessor, we remove unnecessary marco defines generated by Chisel
 * marco defs all start with `, which is a very good pattern.
 * BTW, we will remove all comments
 * We BELIEVE that one should NOT use /(division) in verilog, so we will delete /.
 * */

void preprocess(char **source_buffer) {
    char *ret = NULL;
    ret = (char *)(malloc(FILE_MAX_SIZE));
    int ret_offset = 0;

    int ifdef_count = 0; // record how many ifdefs have we met
    // we will ignore all contents between any ifdefs and endifs
    char c;
    while ((c = fgetc(source_file)) != EOF) {
        if (c == '`') {
            // the begin of a marco
            c = fgetc(source_file);
            // identify the type of marco
            switch (c) {
                case 'd':
                    while (fgetc(source_file) != '\n');
                    break; // define, skip until we got to the end of the line
                case 'i':
                    ++ifdef_count;
                    break; // ifdef begin, we do not need to deal with the reset, for ifdef_count must be above 1
                case 'e':
                    if (fgetc(source_file) == 'l') break; // skip else
                    --ifdef_count;
                    for (int j = 0; j < 4; ++j) {fgetc(source_file);} // skip `endif
                    break; // ifdef end
            }
        } else if (c == '/') {
            // comments
            while (fgetc(source_file) != '\n');
            ret[ret_offset++] = '\n';
        } else if (ifdef_count == 0) {
            ret[ret_offset++] = c;
        }
    }
    ret[ret_offset] = '\n'; // string that ends with 0
    ret[ret_offset + 1] = 0;
    *source_buffer = ret;
}